language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

before_script:
  - pip install -r dev-requirements.txt

script:
  - >
      py.test --cov rfc3986 tests/
      coverage report -m --fail-under 100

notifications:
  on_success: change
  on_failure: always
