language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

before_script:
  - pip install -r dev-requirements.txt

script:
  - >
      if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
        py.test test/
      else
        py.test -n 4 --cov rfc3986 tests/
        coverage report -m --fail-under 100
      fi

notifications:
  on_success: change
  on_failure: always
